version: 0.2

env:
  secrets-manager:
     AWS_ECR_URI: "aws_ecr_uri"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr-public get-login-password --region eu-north-1 | docker login --username AWS --password-stdin $AWS_ECR_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image          
      - docker build -t marvin-hello-world .
      - docker tag marvin-hello-world:latest $AWS_ECR_URI/marvin-hello-world:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR
      - docker push $AWS_ECR_URI/marvin-hello-world:latest